### ISSUE TITLE
BUG: flatgeobuffer doesn't seem to write/read? rows with None nor empty geometry

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#226]
Flatgeobuffer doesn't seem to write/read? rows with None nor empty geometries.

I'm not really familiar with the format, but it seems to be an upstream issue. I was also able to reproduce using ogr2ogr, so I created an upstream bug as well.

```
import geopandas as gpd
import pyogrio

wkts = ["Point (0 0)", None, "Point Empty"]
column_data = {"idx": [str(idx) for idx in range(len(wkts))]}
gdf = gpd.GeoDataFrame(
    column_data, geometry=gpd.GeoSeries.from_wkt(wkts), crs="EPSG:4326"
)
pyogrio.write_dataframe(gdf, "test.fgb")
result_gdf = pyogrio.read_dataframe("test.fgb")
print(gdf)
print(result_gdf)
```
Output:
```
  idx                 geometry
0   0  POINT (0.00000 0.00000)
1   1                     None
2   2              POINT EMPTY
  idx                 geometry
0   0  POINT (0.00000 0.00000)
```

**Comment by theroggy** [comment]
Was looked at upstream, with the following conclusion:
`Now gdal throws an error when attempting to write null geoms to a FlatGeobuf with a spatial index. Null geoms were also ignored when not requesting spatial index, this is fixed.`

This was implemented in the following PR: https://github.com/OSGeo/gdal/pull/7483

Verified with the following script:
```
import geopandas as gpd
import pyogrio

wkts = ["Point (0 0)", None, "Point Empty"]
column_data = {"idx": [str(idx) for idx in range(len(wkts))]}
gdf = gpd.GeoDataFrame(
    column_data, geometry=gpd.GeoSeries.from_wkt(wkts), crs="EPSG:4326"
)

# Without spatial index, they can be written
pyogrio.write_dataframe(gdf, "test.fgb", layer_options={"spatial_index": False})
result_gdf = pyogrio.read_dataframe("test.fgb")
print(gdf)
print(result_gdf)

# With spatial index: error
pyogrio.write_dataframe(gdf, "test.fgb", layer_options={"spatial_index": True})
```
Output:
```
  idx                 geometry
0   0  POINT (0.00000 0.00000)
1   1                     None
2   2              POINT EMPTY
  idx                 geometry
0   0  POINT (0.00000 0.00000)
1   1                     None
2   2              POINT EMPTY
Traceback (most recent call last):
  File "C:\Users\PIEROG\Projects\github\pyogrio\local\fgb_None_empty.py", line 17, in <module>
    pyogrio.write_dataframe(gdf, "test.fgb", layer_options={"spatial_index": True})
  File "C:\Users\PIEROG\Projects\github\pyogrio\pyogrio\geopandas.py", line 420, in write_dataframe
    write(
  File "C:\Users\PIEROG\Projects\github\pyogrio\pyogrio\raw.py", line 404, in write
    ogr_write(
  File "pyogrio\\_io.pyx", line 1828, in pyogrio._io.ogr_write
    raise FeatureError(f"Could not add feature to layer at index {i}: {exc}") from None
pyogrio.errors.FeatureError: Could not add feature to layer at index 1: ICreateFeature: NULL geometry not supported with spatial index
```
