### ISSUE TITLE
Unable to install with pip (ValueError: 'pyogrio/_err.pyx' doesn't match any files)

### ISSUE THREAD

**Issue by kylebarron** [geopandas/pyogrio#76]
Seems like the cython compilation is trying to find a file that doesn't exist? This might be an issue with the `MANIFEST.in` not including the right files?

Here are the files included in the sdist from pip:
```
> extract pyogrio-0.3.0.tar.gz
x pyogrio-0.3.0/
x pyogrio-0.3.0/LICENSE
x pyogrio-0.3.0/MANIFEST.in
x pyogrio-0.3.0/PKG-INFO
x pyogrio-0.3.0/README.md
x pyogrio-0.3.0/pyogrio/
x pyogrio-0.3.0/pyogrio/__init__.py
x pyogrio-0.3.0/pyogrio/_env.py
x pyogrio-0.3.0/pyogrio/_err.c
x pyogrio-0.3.0/pyogrio/_geometry.c
x pyogrio-0.3.0/pyogrio/_io.c
x pyogrio-0.3.0/pyogrio/_ogr.c
x pyogrio-0.3.0/pyogrio/_version.py
x pyogrio-0.3.0/pyogrio/core.py
x pyogrio-0.3.0/pyogrio/errors.py
x pyogrio-0.3.0/pyogrio/geopandas.py
x pyogrio-0.3.0/pyogrio/raw.py
x pyogrio-0.3.0/pyogrio.egg-info/
x pyogrio-0.3.0/pyogrio.egg-info/PKG-INFO
x pyogrio-0.3.0/pyogrio.egg-info/SOURCES.txt
x pyogrio-0.3.0/pyogrio.egg-info/dependency_links.txt
x pyogrio-0.3.0/pyogrio.egg-info/requires.txt
x pyogrio-0.3.0/pyogrio.egg-info/top_level.txt
x pyogrio-0.3.0/pyproject.toml
x pyogrio-0.3.0/setup.cfg
x pyogrio-0.3.0/setup.py
x pyogrio-0.3.0/versioneer.py
```

```
> pip install pyogrio
Collecting pyogrio
  Using cached pyogrio-0.3.0.tar.gz (322 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/Users/kbarron/tmp/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/kbarron/tmp/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/kbarron/tmp/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 124, in <module>
          ext_modules = cythonize(
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/zl/4x9vw27j60n7h41pd6ntb_pc0000gp/T/pip-build-env-dxorfonw/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pyogrio/_err.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jorisvandenbossche** [comment]
I think that should be fixed on the main branch. See eg the sdist in the artifact at https://github.com/geopandas/pyogrio/actions/runs/2197584153. We now only include the original cython files, and not any already cythonized/compiled file.

**Comment by jorisvandenbossche** [comment]
And that artifact also includes some wheels you are always welcome to test out! ;)

**Comment by kylebarron** [comment]
I was able to install from main, thanks!

Didn't try the wheels but guessing the sdist will be easier to install so that the geos matches pygeos and shapely

**Comment by jorisvandenbossche** [comment]
> guessing the sdist will be easier to install so that the compiled geos matches pygeos and shapely

For pyogrio it's mainly GDAL that you need to ensure is available. GDAL also depends on GEOS, but as we only use WKB to transfer data from GDAL to Python, it's not very important that the GEOS from GDAL and the GEOS from pygeos/shapely matches.
